Repository chingu-voyages/v43-tier1-team-08, pull requests merged in 2023-03, with the labels that each got.

#38 Fix - Add script link to html
  index.html
Labels: task

#37 Fix - Match javascript variables to form ids
  app.js
Labels: task

#41 Fix story from words javascript
  app.js
  index.html
Labels: task

#43 Refactor app.js by changing variable name storyText to storyHTML
  app.js
Labels: task

#58 Feat/49 stories with any number of blanks tf
  app.js
  third.html
Labels: feature

#57 Added Homepage w/ HTML Functionality + CSS
  home.css
  index.html
  second.html
Labels: feature

#63 Added Navbar, Instructions page & Team page
  home.css
  index.html
  instructions.html
  ourteam.html
  second.html
  style.css
Labels: enhancement, feature, cleanup

#69 Five stories
  app.js
  data/data-template.json
  data/data.json
Labels: bug, feature
